### ISSUE TITLE
ERR_OUT_OF_RANGE when loading map

### ISSUE THREAD

**Issue by keneanung** [Delwing/discord-mudlet-map#4]
Loading an already downloaded map produced this error:

```
RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 7461937. Received 7461941
    at new NodeError (node:internal/errors:371:5)
    at boundsError (node:internal/buffer:86:9)
    at Buffer.readInt32BE (node:internal/buffer:482:5)
    at ReadBuffer.readInt32BE (/workspaces/map-discord-bot/node_modules/qtdatastream/src/buffer.js:48:32)
    at Function.read (/workspaces/map-discord-bot/node_modules/qtdatastream/src/types.js:236:19)
    at readRoom (/workspaces/map-discord-bot/node_modules/mudlet-map-binary-reader/map-reader.js:140:21)
    at Object.module.exports [as read] (/workspaces/map-discord-bot/node_modules/mudlet-map-binary-reader/map-reader.js:221:17)
    at /workspaces/map-discord-bot/node_modules/discord-mudlet-map/maps/prepare-map.js:32:37
    at new Promise (<anonymous>)
    at /workspaces/map-discord-bot/node_modules/discord-mudlet-map/maps/prepare-map.js:31:9 {
  code: 'ERR_OUT_OF_RANGE'
}
```
Restarting the bot did not throw the error again. Instead, it loaded the map just fine.

This happened when loading this [map](https://github.com/Delwing/discord-mudlet-map/files/7332439/map.zip)

**Comment by Delwing** [comment]
I think version `0.0.7` will address that, if it doesn't, please reopen.
